# Generated by Django 5.1 on 2024-09-07 08:10

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_completed_task_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateField(default=now),
            preserve_default=False,
        ),
    ]
