# Generated by Django 5.1 on 2024-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_task_end_time_remove_task_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='未着手', max_length=10),
        ),
    ]
