# Generated by Django 5.1 on 2024-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_work_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
